//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeTable_DB_Source
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class cnOrarend : DbContext
    {
        public cnOrarend()
            : base("name=cnOrarend")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tantargy> Tantargyak { get; set; }
        public virtual DbSet<Tanterem> Tantermek { get; set; }
        public virtual DbSet<HaziFeladat> HaziFeladatok { get; set; }
        public virtual DbSet<Tanora> Tanorak { get; set; }
    }
}
